### ISSUE TITLE
Bug when reporting unadjusted p-vals on Stata version 14 or older

### ISSUE THREAD

**Issue by maxkeber** [reifjulian/wyoung#13]
Hi there,

I noticed what appears to be an error in the unadjusted p-values which occurs when including standard errors. Take the example included in your Stata help file:

`sysuse auto.dta, clear`
`wyoung mpg headroom turn, cmd(regress OUTCOMEVAR displacement length, cluster(rep78)) cluster(rep78) familyp(displacement) bootstraps(100) seed(20)`

Let's then take the example where headroom is the outcome variable. The wyoung table produces an unadjusted p-value of .25000982 for the coefficient on displacement. But if we run the underlying model outside of the wyoung package:

`regress headroom displacement length, cluster(rep78)`

then we get a p-value of 0.314 for the coefficient on displacement. It appears that the coefficient and standard errors are coming through correctly to the wyoung table, but unless I'm misunderstanding (apologies if I am missing something obvious!), something is going wrong with the p-value computation.

**Comment by reifjulian** [comment]
Hi Max,

Please confirm that you are running the latest version (1.3.2 16jun2021) by typing `which wyoung` at the prompt.

I was unable to confirm your error. I get 0.314 for both, see code and output below.

```stata
sysuse auto.dta, clear
wyoung mpg headroom turn, cmd(regress OUTCOMEVAR displacement length, cluster(rep78)) cluster(rep78) familyp(displacement) bootstraps(100) seed(20)
regress headroom displacement length, cluster(rep78)
```

![image](https://github.com/reifjulian/wyoung/assets/42722121/19b167fe-e8dc-4570-abb8-fc93673aac6d)

**Comment by maxkeber** [comment]
Thanks for your quick reply! 

I can confirm I am using the right version. Running which wyoung yields the output: 

c:\ado\plus\w\wyoung.ado
*! wyoung 1.3.2 16jun2021 by Julian Reif

I am still getting the same issue, but am not sure why we are getting different results. When I run the exact lines of code from your reply, I get the following output:

![image](https://github.com/reifjulian/wyoung/assets/56857049/466390e0-808b-4b9f-b8c2-488af2b761f6)
![image](https://github.com/reifjulian/wyoung/assets/56857049/586cb886-7d1a-41ab-9475-1e140800a19e)

where you can see I get p=.25 when using wyoung instead of .314.

Are there any Stata settings you can think of that might be throwing this off for me, but not for you?

Note: I tried it on another computer with Stata 17 and it worked correctly as it did for you. Maybe it's something to do with me using an older version of Stata (14)? Though I would expect since the wyoung version is the same, it should still work on 14...

**Comment by reifjulian** [comment]
That is odd. I think you are getting the p-value corresponding to the normal distribution, rather than the t-distribution. No idea why though. The p-value for your example gets calculated on lines 373-378 of `wyoung.ado`.

https://github.com/reifjulian/wyoung/blob/a9585a397b50d1aeb3374faa2469657cedf1ccf4/src/wyoung.ado#L373-L378

So, for your example the relevant code is:
```stata
sysuse auto.dta, clear
regress headroom displacement length, cluster(rep78)
lincom displacement
scalar my_pval = r(p)
di my_pval
```

Stata 18 documentation notes that if `e(df_r)` is not available after running the regression, the `lincom` command will assume normality.  That is basically the same as a very large df_r, and indeed produces your 0.25 p-value:

```stata
sysuse auto.dta, clear
regress headroom displacement length, cluster(rep78)
lincom displacement, df(99999)
scalar my_pval = r(p)
di my_pval
```

I don't know if/why that is happening for you though. Can you confirm that the first code chunk above (the one with the `lincom` command that does not specify `df()`) gives you the 0.314 p-value on your Stata 14 machine?

**Comment by maxkeber** [comment]
Interesting and very strange -- thanks for that super helpful catch of what's going on and for trying to work through this with me, I really appreciate it! 

That is indeed the issue -- the first chunk of code produces .314 and the second is giving me .25.

I tried resetting all my system parameters back to defaults using `set_defaults _all, perm` and updating all of my user-written packages with `adoupdate, update` but the issue still remains. I can't figure out what other setting I might have that would be causing this. Let me know if you have any other thoughts. That said, I recognize this is an issue with my personal machine and not your command so I can also definitely migrate this to a Stata forum.

**Comment by reifjulian** [comment]
To clarify, are you saying that you get different p-vals when running the following code chunk on Stata 14 vs Stata 17?
```stata
sysuse auto.dta, clear
regress headroom displacement length, cluster(rep78)
lincom displacement
scalar my_pval = r(p)
di my_pval
```

**Comment by maxkeber** [comment]
No, I get .314 on both Stata 14 and 17 for that chunk of code

**Comment by reifjulian** [comment]
Unfortunately, this is difficult to debug since I cannot replicate the problem. Here is something that may work. Type `which wyoung` on your Stata 14 machine (the one that produces the wrong p-value) to find the location of `wyoung.ado`. Open that file in Stata or a text editor, and add the following line of code right after line 377:
```stata
noi di `p_`k''
```

Save your changes to `wyoung.ado`. Then run the following code chunk on the Stata 14 machine and send me the `wyoung.log` file. Comparing it to my own might shed light on the issue.

```stata
cap log close
sysuse auto.dta, clear

set trace on
set tracedepth 1
log using "$DROPBOX/wyoung.log", replace
wyoung mpg headroom turn, cmd(regress OUTCOMEVAR displacement length, cluster(rep78)) cluster(rep78) familyp(displacement) bootstraps(100) seed(20)
set trace off
```

**Comment by maxkeber** [comment]
Done, see attached.
[wyoung.log](https://github.com/reifjulian/wyoung/files/13979322/wyoung.log)

**Comment by reifjulian** [comment]
Ok, the bug does appear to lie in lines 373-378. For some reason your setup is not retrieving that p-value after the `lincom` command. Let's make one more change to `wyoung.ado`. Replace line 373 of `wyoung.ado`: 
```stata
cap lincom `familyp_`k''
```
with these two lines of code:
```stata
noi lincom `familyp_`k''
noi return list
```

Then run again the following code chunk to produce a new log file. I've added a `program drop _all` statement to it to ensure you use the new `wyoung.ado` file:
```stata
program drop _all
cap log close
sysuse auto.dta, clear

set trace on
set tracedepth 1
log using "$DROPBOX/wyoung.log", replace
wyoung mpg headroom turn, cmd(regress OUTCOMEVAR displacement length, cluster(rep78)) cluster(rep78) familyp(displacement) bootstraps(100) seed(20)
set trace off
```
This should reveal the bug.

**Comment by maxkeber** [comment]
Ok done -- see attached 
[wyoung.log](https://github.com/reifjulian/wyoung/files/13979866/wyoung.log)

**Comment by reifjulian** [comment]
Thanks! Ok, it is now clear what the bug is. `lincom` in Stata 14 does not store the p-value in `r(p)`. Looks like `r(p)` did not become available until Stata 15, as confirmed by the [Stata 15 manual](https://www.stata.com/manuals15/r.pdf). So bottom line, this bug should not arise provided you are using Stata 15 or newer.

I will think about how/whether to address this in `wyoung`.

**Comment by maxkeber** [comment]
I see -- thanks for helping to root out this issue! I'll look to use Stata 15 or higher in the meantime. Would be great if you could let me know here if/when you're able to fix this bug.

Thanks again!!

**Comment by reifjulian** [comment]
I made an edit that I think should fix this bug. You can install the fix by running this code:
```stata
net install wyoung, from("https://raw.githubusercontent.com/reifjulian/wyoung/development") replace
```
Type `program drop _all`, and then `which wyoung`, to confirm you are running the updated version (`1.3.3 18jan2024`). You can then try rerunning the code chunk on Stata 14. Does that fix the problem?

**Comment by maxkeber** [comment]
That does fix the problem! Amazing, thank you so much for all your help and super fast fix -- really much appreciated!

**Comment by reifjulian** [comment]
Great, thank you for confirming! I have pushed this fix to the master version of `wyoung` on Github.
